config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create', as: :create

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update', as: :update

  delete 'tasks/:id', to: 'tasks#delete', as: :delete
  get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :delete]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @tasks = Task.new
  end

  def create
    @tasks = Task.new(task_params)
  end

  def edit
  end

  def update
    @tasks.update(task_params)
  end

  def delete
    @tasks.destroy
  end
end

private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

def set_task
  @tasks = Task.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container w-50">
<h1 class="mt-4 mb-4 text-success">Edit task</h1>

<%= form_with model: @tasks do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control mb-4" %>
  <%= f.label :details %>
  <%= f.text_field :details, class: "form-control" %>
  <div class="checkbox">
    <label class="mt-2" ><%= f.check_box :completed %> Completed</label>
  </div>
  <%= f.submit class: "btn btn-success mt-4" %>
<% end %>

<button type="button" class="btn btn-light mt-2">
<%= link_to "List all the tasks", tasks_path, class:"text-decoration-none text-dark" %>
</button>

</div>

app/views/tasks/index.html.erb
<div class="container w-50">
<h1 class="mt-2 text-success">My Tasks</h1>

  <div class="card d-grid gap-2 "><% @tasks.each do |task| %>
    <ul class="p-2 bg-light"><%= link_to task.title, task_path(task.id), class:"text-decoration-none text-dark"%>
    </ul>
    <% end %>
  </div>

  <button type="button" class="btn btn-outline-success mt-2">
    <%= link_to "Add a new task", new_path, class:"text-decoration-none text-dark" %>
  </button>
</div>

app/views/tasks/new.html.erb
<div class="container w-50">
<h1 class="mt-4 mb-4 text-success">New Task</h1>

<%= form_with model: @tasks do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control mb-4" %>
  <%= f.label :details %>
  <%= f.text_field :details, class: "form-control " %>
  <%= f.submit class: "btn btn-success mt-2" %>
<% end %>

<button type="button" class="btn btn-light mt-2">
  <%= link_to "Back to the list", tasks_path, class:"text-decoration-none text-dark" %>
</button>

</div>

app/views/tasks/show.html.erb
<div class="container w-50 mt-2">
  <h1 class="border-round text-success mt-4"><%= @tasks.title %></h1>
  <div class="card py-4 px-4">
  <p class="card text-dark bg-light p-3"><%= @tasks.details %></p>
  <p class="card text-dark bg-light p-3">Completed: <%= @tasks.completed %></p>
  </div>

  <div class="btn-group-vertical">
  <button type="button" class="btn btn-light mt-2"><%= link_to "Back to List", tasks_path, class:"text-decoration-none text-dark"%>
  <button type="button" class="btn btn-success mt-2"><%= link_to "Add a new task", new_path, class:"text-decoration-none text-white" %>
  <button type="button" class="btn btn-primary mt-2"><%= link_to "Edit task", edit_path, class:"text-decoration-none text-white" %>
  <button type="button" class="btn btn-danger mt-2"><%= link_to "Delete", delete_path, class:"text-decoration-none text-white", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>

</div>